on:
  push:
    branches:
      - main

jobs:
  get_tweets:
    name: 'Retrieve Tweets and Embeds'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: '../../dist/index.js'