on:
  push:
    branches: 
      - main

jobs:
  get_tweets:
    name: 'Retrieve Tweets and Embeds'
    runs-on: ubuntu-latest
    environment: primary
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v2
      - name: Run action
        uses: ./
        env:
          BEARER: ${{ secrets.BEARER }}
      - name: setup git config
        run: |
          git config user.name "Jason Jones"
          git config user.email "jasonajones73@gmail.com"

      - name: commit
        run: |
          git add tweets.json embedCode.json
          git diff-index --quiet HEAD || git commit -m 'Update tweets and embeds'
          git push origin main